vectara:
  corpus_id: 171
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://studentservices.stanford.edu"]
  url_regex: [".*studentservices.stanford.edu.*"]
  delay: 1
  pages_source: crawl
  max_depth: 4
  extraction: playwright
