vectara:
  corpus_id: 172
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://admission.ucla.edu"]
  url_regex: [".*admission.ucla.edu.*"]
  delay: 1
  pages_source: crawl
  max_depth: 4
  extraction: playwright
