vectara:
  corpus_id: 194
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: docs

docs_crawler:
  base_urls: ["https://kubernetes.io/docs/home/"]
  url_regex: ["https://kubernetes.io/docs/.*", "https://kubernetes.io/blog/.*"]
  extensions_to_ignore: ["php", "java", "py", "js", "scala"]
  docs_system: MkDocs

