vectara:
  corpus_id: 196
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: docs

docs_crawler:
  base_urls: ["https://pytorch.org/docs/stable/index.html"]
  url_regex: ["https://pytorch.org/docs/.*"]
  extensions_to_ignore: ["php", "java", "js", "scala"]
  docs_system: AsciiDocs

