vectara:
  corpus_id: 192
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: docs

docs_crawler:
  base_urls: ["https://react.dev"]
  url_regex: ["https://react.dev.*"]
  extensions_to_ignore: ["php", "java", "py", "js"]
  docs_system: docusaurus

