vectara:
  corpus_id: 195
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: docs

docs_crawler:
  base_urls: ["https://www.elastic.co/guide"]
  url_regex: ["https://www.elastic.co/guide.*"]
  extensions_to_ignore: ["php", "java", "py", "js", "scala"]
  docs_system: AsciiDocs

