vectara:
  corpus_id: 163
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: docs

docs_crawler:
  base_urls:
    [
      "https://docs.langchain.com/docs",
      "https://python.langchain.com",
      "https://js.langchain.com",
      "https://blog.langchain.dev",
    ]
  url_regex:
    [
      ".*langchain.com/docs.*",
      ".*python.langchain.com.*",
      ".*js.langchain.com.*",
      ".*blog.langchain.dev.*",
    ]
  extensions_to_ignore: ["md", "rst", "ipynb"]
  docs_system: docusaurus
